INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ('Engineering');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ('HR');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ('Management');

INSERT INTO EMPLOYEE (FIRST_NAME, MIDDLE_NAME, LAST_NAME, ADDRESS, DEPARTMENT_ID) VALUES ('John', 'De', 'Ln', 'Santa Clara, CA', 1);
INSERT INTO EMPLOYEE (FIRST_NAME, MIDDLE_NAME, LAST_NAME, ADDRESS, DEPARTMENT_ID) VALUES ('Lucy', 'Ly', 'Hul', 'Bloomington, IL', 2);
INSERT INTO EMPLOYEE (FIRST_NAME, MIDDLE_NAME, LAST_NAME, ADDRESS, DEPARTMENT_ID) VALUES ('Sam', 'Na', 'Druv', 'Atlanta, GA', 3);