INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ('Engineering');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ('HR');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ('Management');

INSERT INTO EMPLOYEE (FIRST_NAME, MIDDLE_NAME, LAST_NAME, DEPARTMENT_ID) VALUES ('John', 'De', 'Ln', 1);
INSERT INTO EMPLOYEE (FIRST_NAME, MIDDLE_NAME, LAST_NAME, DEPARTMENT_ID) VALUES ('Lucy', 'Ly', 'Hul', 2);
INSERT INTO EMPLOYEE (FIRST_NAME, MIDDLE_NAME, LAST_NAME, DEPARTMENT_ID) VALUES ('Sam', 'Na', 'Druv', 3);