INSERT INTO EMPLOYEE (FIRST_NAME, MIDDLE_NAME, LAST_NAME) VALUES ('John', 'De', 'Ln');
INSERT INTO EMPLOYEE (FIRST_NAME, MIDDLE_NAME, LAST_NAME) VALUES ('Lucy', 'Ly', 'Hul');
INSERT INTO EMPLOYEE (FIRST_NAME, MIDDLE_NAME, LAST_NAME) VALUES ('Sam', 'Na', 'Druv');