DROP TABLE EMPLOYEE IF EXISTS;

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID BIGINT AUTO_INCREMENT,
    FIRST_NAME  VARCHAR2(255) NOT NULL,
    MIDDLE_NAME VARCHAR2(255),
    LAST_NAME   VARCHAR2(255) NOT NULL,
    ADDRESS   VARCHAR2(255),
    DEPARTMENT_ID BIGINT,
    PRIMARY KEY (EMPLOYEE_ID)
);

DROP TABLE DEPARTMENT IF EXISTS;

CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID   BIGINT AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR2(255) NOT NULL,
    PRIMARY KEY (DEPARTMENT_ID)
);

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT DEPARTMENT_ID_FK
        FOREIGN KEY (DEPARTMENT_ID)
            REFERENCES DEPARTMENT


